import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/Components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ThemeProvider
        attribute={'class'}
        enableSystem>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
